version: "3"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  bot:
    build: .
    depends_on:
      - db
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: host.docker.internal
    restart: unless-stopped
    volumes:
      - bot-data:/usr/src/app/data

volumes:
    db-data:
    bot-data: