name: Deploy Discord Commands

on:
  push:
    paths:
      - 'commands/**'
      - 'deploy-commands.js'
    branches:
      - main
      - master
  pull_request:
    paths:
      - 'commands/**'
      - 'deploy-commands.js'
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21' # or your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run deployment script
        run: node deploy-commands.js
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          GUILD_ID: ${{ secrets.GUILD_ID }}